#!/bin/bash

# Execute Asana Field Audit Synchronization
# Updates example-company Foundation Project tasks with comprehensive field audit findings

echo "🚀 Asana Field Audit Synchronization"
echo "===================================="
echo ""

# Check dependencies
echo "🔍 Checking dependencies..."

if ! command -v node &> /dev/null; then
    echo "❌ Error: Node.js is not installed"
    echo "Please install Node.js: https://nodejs.org/"
    exit 1
fi

echo "✅ Node.js found: $(node --version)"

# Check for Asana access token
if [ -z "$ASANA_ACCESS_TOKEN" ]; then
    echo ""
    echo "❌ ASANA_ACCESS_TOKEN not found in environment"
    echo ""
    echo "🔧 Fix with Asana Connection Manager:"
    echo "   ./.claude-plugins/cross-platform-plugin/scripts/lib/asana-connection-manager.sh validate"
    echo ""
    echo "Or load from .env:"
    echo "   set -a && source .env && set +a"
    echo ""
    exit 1
fi

# Validate token format (basic check)
if [[ ! "$ASANA_ACCESS_TOKEN" =~ ^2/ ]]; then
    echo "❌ ASANA_ACCESS_TOKEN format invalid (should start with '2/')"
    echo "   Run: ./.claude-plugins/cross-platform-plugin/scripts/lib/asana-connection-manager.sh fix"
    exit 1
fi

# Make scripts executable
chmod +x ./asana-field-audit-sync.js
chmod +x ./update-asana-field-audit.js

echo ""
echo "📝 Executing field audit synchronization..."
echo "Target: example-company Foundation Project"
echo "Tasks: Cleanup/Remediation, Deduplication, Data Quality"
echo ""

# Execute the synchronization
node ./asana-field-audit-sync.js

exit_code=$?

echo ""
if [ $exit_code -eq 0 ]; then
    echo "✅ Synchronization completed successfully!"
    echo ""
    echo "📊 Summary of Updates:"
    echo "• Cleanup, Remediation & Deprecation task - Updated with comprehensive audit completion"
    echo "• Account & Contact Deduplication task - Updated with duplicate field findings"  
    echo "• Data Quality Rules task - Updated with quality assessment results"
    echo "• Time tracking information added to all relevant tasks"
    echo ""
    echo "🎯 Next Steps:"
    echo "1. Review the updated tasks in Asana"
    echo "2. Prioritize cleanup activities based on audit findings"
    echo "3. Plan implementation of recommended field consolidations"
    echo "4. Execute high-priority remediation tasks"
    echo ""
    echo "📁 For detailed findings, refer to the field audit reports generated by sfdc-revops-auditor"
else
    echo "❌ Synchronization failed with exit code $exit_code"
    echo "Check the error messages above for details"
    echo ""
    echo "💡 Troubleshooting:"
    echo "1. Verify ASANA_ACCESS_TOKEN is valid"
    echo "2. Check network connectivity"
    echo "3. Ensure Asana project access permissions"
    echo "4. Review console output for specific error details"
fi

echo ""
echo "Script completed at: $(date)"