#!/usr/bin/env node
/**
 * Execution Receipt — Deterministic Proof of Investigation Execution
 *
 * Generates and verifies cryptographic receipts proving that investigation
 * helpers actually executed queries against a Salesforce org. Receipts are
 * tied to real execution output, not narrative text.
 *
 * Design:
 *   - Receipt is a JSON structure with an integrity hash (SHA-256)
 *   - Hash is computed over canonical JSON of the receipt fields
 *   - The hash proves the receipt was generated by this code, not by LLM prose
 *     (an LLM would need to compute the exact SHA-256 matching the field values)
 *   - Receipt includes execution metadata: org, timestamp, branch results, counts
 *   - Verification re-computes the hash and checks freshness
 *
 * Receipt lifecycle:
 *   1. Execution helper runs queries → collects results
 *   2. generateReceipt(executionResult) → receipt JSON with integrity hash
 *   3. Specialist includes receipt in output (as fenced JSON block)
 *   4. SubagentStop hook extracts receipt → verifyReceipt(receipt) → pass/fail
 *
 * @version 1.0.0
 */

const crypto = require('crypto');

const RECEIPT_VERSION = '1.0';
const RECEIPT_MARKER = '<!-- EXECUTION_RECEIPT_V1';
const RECEIPT_END_MARKER = 'EXECUTION_RECEIPT_V1 -->';
const MAX_AGE_MS = 30 * 60 * 1000; // 30 minutes — receipt must be fresh

/**
 * Deep-sort all object keys recursively for canonical JSON.
 * @param {*} obj - Value to canonicalize
 * @returns {*} Canonicalized value
 */
function deepSortKeys(obj) {
  if (obj === null || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(deepSortKeys);
  const sorted = {};
  for (const key of Object.keys(obj).sort()) {
    sorted[key] = deepSortKeys(obj[key]);
  }
  return sorted;
}

/**
 * Compute SHA-256 hash of the canonical receipt payload.
 * Uses deep key sorting to ensure deterministic serialization.
 * @param {object} payload - Receipt fields (without integrityHash)
 * @returns {string} hex-encoded SHA-256 hash
 */
function computeHash(payload) {
  const canonical = JSON.stringify(deepSortKeys(payload));
  return crypto.createHash('sha256').update(canonical, 'utf8').digest('hex');
}

/**
 * Generate an execution receipt from real investigation results.
 *
 * @param {object} executionResult - Output from investigationFanOut or safeExecMultipleQueries
 * @param {object} options - { helper?: string }
 * @returns {object} Receipt with integrity hash
 */
function generateReceipt(executionResult, options = {}) {
  const {
    status,
    orgAlias,
    totalQueries,
    succeededCount,
    failedCount,
    succeeded = {},
    failed = {},
    fallbacks = [],
    durationMs
  } = executionResult;

  // Build branch summary from actual results
  const branches = [];
  for (const [name, result] of Object.entries(succeeded)) {
    branches.push({
      name,
      status: 'success',
      recordCount: result.totalSize || result.records?.length || 0,
      usedFallback: result.usedFallback || false
    });
  }
  for (const [name, result] of Object.entries(failed)) {
    branches.push({
      name,
      status: 'failed',
      recordCount: 0,
      failureType: result.failureType || 'unknown',
      error: (result.error || '').substring(0, 100)
    });
  }

  // Build the receipt payload (everything except the hash)
  const payload = {
    version: RECEIPT_VERSION,
    type: 'investigation-execution-receipt',
    orgAlias: orgAlias || 'unknown',
    timestamp: new Date().toISOString(),
    helper: options.helper || 'investigation-fan-out@1.0.0',
    executionStatus: status || 'unknown',
    queries: {
      total: totalQueries || 0,
      succeeded: succeededCount || 0,
      failed: failedCount || 0
    },
    branches,
    fallbackCount: fallbacks?.length || 0,
    durationMs: durationMs || 0
  };

  // Compute integrity hash over the payload
  const integrityHash = 'sha256:' + computeHash(payload);

  return {
    ...payload,
    integrityHash
  };
}

/**
 * Generate a receipt from safeExecMultipleQueries output format.
 *
 * @param {object} multiResult - { results, succeeded, failed, partial, allSucceeded, allFailed }
 * @param {string} orgAlias - Target org
 * @param {object} options - { helper?: string }
 * @returns {object} Receipt with integrity hash
 */
function generateReceiptFromMultiQuery(multiResult, orgAlias, options = {}) {
  const { results = {}, succeeded = [], failed = [] } = multiResult;

  let status;
  if (failed.length === 0) status = 'complete';
  else if (succeeded.length === 0) status = 'failed';
  else status = 'partial';

  const succeededMap = {};
  for (const name of succeeded) {
    succeededMap[name] = results[name] || { totalSize: 0, records: [] };
  }
  const failedMap = {};
  for (const name of failed) {
    failedMap[name] = results[name] || { error: 'unknown', failureType: 'unknown' };
  }

  return generateReceipt({
    status,
    orgAlias,
    totalQueries: succeeded.length + failed.length,
    succeededCount: succeeded.length,
    failedCount: failed.length,
    succeeded: succeededMap,
    failed: failedMap,
    fallbacks: [],
    durationMs: 0
  }, { helper: options.helper || 'safeExecMultipleQueries@1.0.0', ...options });
}

/**
 * Verify an execution receipt.
 *
 * Checks:
 *   1. Required fields present
 *   2. Version match
 *   3. Integrity hash matches re-computed hash
 *   4. Timestamp freshness (within MAX_AGE_MS)
 *   5. At least one query was attempted
 *
 * @param {object} receipt - Receipt object to verify
 * @param {object} options - { maxAgeMs?: number, requireSuccess?: boolean }
 * @returns {object} { valid: boolean, reason?: string, classification: string }
 */
function verifyReceipt(receipt, options = {}) {
  const maxAgeMs = options.maxAgeMs || MAX_AGE_MS;

  // Check 1: Required fields
  if (!receipt || typeof receipt !== 'object') {
    return { valid: false, reason: 'Receipt is null or not an object', classification: 'missing_receipt' };
  }

  const requiredFields = ['version', 'type', 'orgAlias', 'timestamp', 'helper',
                          'executionStatus', 'queries', 'branches', 'integrityHash'];
  for (const field of requiredFields) {
    if (receipt[field] === undefined || receipt[field] === null) {
      return { valid: false, reason: `Missing required field: ${field}`, classification: 'invalid_receipt' };
    }
  }

  // Check 2: Version and type
  if (receipt.version !== RECEIPT_VERSION) {
    return { valid: false, reason: `Unknown receipt version: ${receipt.version}`, classification: 'invalid_receipt' };
  }
  if (receipt.type !== 'investigation-execution-receipt') {
    return { valid: false, reason: `Wrong receipt type: ${receipt.type}`, classification: 'invalid_receipt' };
  }

  // Check 3: Integrity hash
  const { integrityHash, ...payloadFields } = receipt;
  const expectedHash = 'sha256:' + computeHash(payloadFields);
  if (integrityHash !== expectedHash) {
    return { valid: false, reason: 'Integrity hash mismatch — receipt tampered or fabricated', classification: 'tampered_receipt' };
  }

  // Check 4: Timestamp freshness
  const receiptTime = new Date(receipt.timestamp).getTime();
  const now = Date.now();
  if (isNaN(receiptTime)) {
    return { valid: false, reason: 'Invalid timestamp', classification: 'invalid_receipt' };
  }
  if (now - receiptTime > maxAgeMs) {
    return { valid: false, reason: `Receipt expired (age: ${Math.round((now - receiptTime) / 1000)}s, max: ${maxAgeMs / 1000}s)`, classification: 'expired_receipt' };
  }

  // Check 5: At least one query attempted
  if (!receipt.queries || receipt.queries.total === 0) {
    return { valid: false, reason: 'No queries attempted', classification: 'empty_receipt' };
  }

  // Check 6: Execution status
  if (receipt.executionStatus === 'failed' && options.requireSuccess) {
    return { valid: false, reason: 'All queries failed', classification: 'execution_failed' };
  }

  // Valid receipt — classify the execution result
  let classification;
  if (receipt.executionStatus === 'complete') {
    classification = 'valid_complete';
  } else if (receipt.executionStatus === 'partial') {
    classification = 'valid_partial';
  } else if (receipt.executionStatus === 'failed') {
    classification = 'valid_failed';
  } else {
    classification = 'valid_unknown_status';
  }

  return {
    valid: true,
    classification,
    executionStatus: receipt.executionStatus,
    queriesSucceeded: receipt.queries.succeeded,
    queriesFailed: receipt.queries.failed,
    fallbackCount: receipt.fallbackCount || 0
  };
}

/**
 * Format a receipt as an HTML comment block for embedding in agent output.
 * This format is extractable by the proof hook but invisible in rendered markdown.
 *
 * @param {object} receipt - Receipt to format
 * @returns {string} Formatted receipt block
 */
function formatReceiptBlock(receipt) {
  return `${RECEIPT_MARKER}\n${JSON.stringify(receipt)}\n${RECEIPT_END_MARKER}`;
}

/**
 * Extract a receipt from agent output text.
 * Looks for the EXECUTION_RECEIPT_V1 marker.
 *
 * @param {string} text - Agent output text
 * @returns {object|null} Extracted receipt or null
 */
function extractReceiptFromOutput(text) {
  if (!text || typeof text !== 'string') return null;

  const startIdx = text.indexOf(RECEIPT_MARKER);
  if (startIdx === -1) return null;

  const endIdx = text.indexOf(RECEIPT_END_MARKER, startIdx);
  if (endIdx === -1) return null;

  const jsonStr = text.substring(startIdx + RECEIPT_MARKER.length, endIdx).trim();
  try {
    return JSON.parse(jsonStr);
  } catch (e) {
    return null;
  }
}

// CLI entry point
if (require.main === module) {
  const action = process.argv[2];

  if (action === 'verify') {
    // Read receipt from stdin
    let input = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', chunk => { input += chunk; });
    process.stdin.on('end', () => {
      const receipt = extractReceiptFromOutput(input) || (() => {
        try { return JSON.parse(input); } catch (e) { return null; }
      })();

      if (!receipt) {
        console.log(JSON.stringify({ valid: false, reason: 'No receipt found', classification: 'missing_receipt' }));
        process.exit(1);
      }

      const result = verifyReceipt(receipt);
      console.log(JSON.stringify(result, null, 2));
      process.exit(result.valid ? 0 : 1);
    });
  } else if (action === 'test-generate') {
    // Generate a test receipt for verification testing
    const testResult = {
      status: 'complete',
      orgAlias: 'test-org',
      totalQueries: 3,
      succeededCount: 3,
      failedCount: 0,
      succeeded: {
        flows: { totalSize: 10, records: [] },
        triggers: { totalSize: 5, records: [] },
        rules: { totalSize: 8, records: [] }
      },
      failed: {},
      fallbacks: [],
      durationMs: 1234
    };
    const receipt = generateReceipt(testResult, { helper: 'test@1.0.0' });
    console.log(formatReceiptBlock(receipt));
  } else {
    console.error('Usage:');
    console.error('  echo "<output>" | node execution-receipt.js verify');
    console.error('  node execution-receipt.js test-generate');
    process.exit(1);
  }
}

module.exports = {
  generateReceipt,
  generateReceiptFromMultiQuery,
  verifyReceipt,
  formatReceiptBlock,
  extractReceiptFromOutput,
  computeHash,
  RECEIPT_VERSION,
  RECEIPT_MARKER,
  RECEIPT_END_MARKER,
  MAX_AGE_MS
};
