#!/usr/bin/env bash

##
# Package Architecture Audit Deliverables
#
# Packages all architecture audit artifacts into organized, timestamped archive.
# Designed to run as a Stop hook after sfdc-architecture-auditor completes.
#
# Usage:
#   bash package-architecture-audit.sh <working-dir> [--org-alias <alias>]
#
# Inputs:
#   - Working directory containing generated reports
#   - Optional org alias for naming
#
# Outputs:
#   - Timestamped ZIP archive: architecture-audit-{org}-{timestamp}.zip
#   - Copied to instances/{org}/architecture-audits/
#
# Features:
#   - Collects ADRs, health reports, dependency diagrams
#   - Creates structured archive (reports/, diagrams/, data/, metadata/)
#   - Generates package-info.json and README.md
#   - Compresses and archives
##

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function: Print colored message
log_info() {
    echo -e "${GREEN}✓${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
    echo -e "${RED}✗${NC} $1"
}

# Parse arguments
WORKING_DIR="${1:-.}"
ORG_ALIAS="${ORG_ALIAS:-unknown}"

# Check for --org-alias flag
for i in "$@"; do
    case $i in
        --org-alias)
            ORG_ALIAS="${!#}"
            shift
            ;;
    esac
done

# Validate working directory
if [[ ! -d "$WORKING_DIR" ]]; then
    log_error "Working directory not found: $WORKING_DIR"
    exit 1
fi

log_info "Architecture Audit Deliverable Packager"
echo ""
echo "  Working Directory: $WORKING_DIR"
echo "  Org Alias: $ORG_ALIAS"
echo ""

# Generate timestamp
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
ARCHIVE_NAME="architecture-audit-${ORG_ALIAS}-${TIMESTAMP}"
ARCHIVE_DIR="${WORKING_DIR}/${ARCHIVE_NAME}"

log_info "Phase 1: Creating archive structure..."
mkdir -p "${ARCHIVE_DIR}"/{reports,diagrams,data,metadata}

# Phase 2: Collect reports
log_info "Phase 2: Collecting reports..."
REPORT_COUNT=0

# Architecture reports, health scores, ADRs
find "$WORKING_DIR" -maxdepth 1 -type f \( -name "*.md" -o -name "*.html" \) ! -name "*.mmd" \
    -exec cp {} "${ARCHIVE_DIR}/reports/" \; 2>/dev/null && \
    REPORT_COUNT=$(find "${ARCHIVE_DIR}/reports/" -type f | wc -l | tr -d ' ')

log_info "  Collected $REPORT_COUNT reports"

# Phase 3: Collect diagrams
log_info "Phase 3: Collecting diagrams..."
DIAGRAM_COUNT=0

find "$WORKING_DIR" -maxdepth 1 -type f \( -name "*.mmd" -o -name "*.png" -o -name "*.svg" \) \
    -exec cp {} "${ARCHIVE_DIR}/diagrams/" \; 2>/dev/null && \
    DIAGRAM_COUNT=$(find "${ARCHIVE_DIR}/diagrams/" -type f | wc -l | tr -d ' ')

log_info "  Collected $DIAGRAM_COUNT diagrams"

# Phase 4: Collect data files
log_info "Phase 4: Collecting data files..."
DATA_COUNT=0

find "$WORKING_DIR" -maxdepth 1 -type f \( -name "*.json" -o -name "*.csv" \) ! -name "*manifest.json" \
    -exec cp {} "${ARCHIVE_DIR}/data/" \; 2>/dev/null && \
    DATA_COUNT=$(find "${ARCHIVE_DIR}/data/" -type f | wc -l | tr -d ' ')

log_info "  Collected $DATA_COUNT data files"

# Phase 5: Generate package metadata
log_info "Phase 5: Generating package metadata..."

cat > "${ARCHIVE_DIR}/metadata/package-info.json" <<EOF
{
  "packageName": "${ARCHIVE_NAME}",
  "orgAlias": "${ORG_ALIAS}",
  "packageType": "architecture-audit",
  "generatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "generatedBy": "package-architecture-audit.sh",
  "hookType": "Stop",
  "agentName": "sfdc-architecture-auditor",
  "contents": {
    "reports": ${REPORT_COUNT},
    "diagrams": ${DIAGRAM_COUNT},
    "dataFiles": ${DATA_COUNT}
  },
  "version": "1.0.0"
}
EOF

# Phase 6: Generate README
log_info "Phase 6: Generating README..."

cat > "${ARCHIVE_DIR}/README.md" <<EOF
# Architecture Audit Deliverables

**Organization:** ${ORG_ALIAS}
**Generated:** $(date)
**Package:** ${ARCHIVE_NAME}

## Contents

- **reports/** (${REPORT_COUNT} files) - Architecture health reports, ADRs, recommendations
- **diagrams/** (${DIAGRAM_COUNT} files) - Dependency diagrams, architecture visualizations
- **data/** (${DATA_COUNT} files) - Raw data exports, metrics
- **metadata/** - Package information

## Generated By

This package was automatically generated by the \`sfdc-architecture-auditor\` agent
using the \`package-architecture-audit.sh\` Stop hook.

## Usage

Review the reports in the **reports/** directory first for executive summary and
key findings. Reference diagrams for visual understanding of architecture patterns
and dependencies.

## Support

For questions about this audit, contact the RevOps team or consult the
architecture runbook at \`instances/${ORG_ALIAS}/ARCHITECTURE_RUNBOOK.md\`.
EOF

# Phase 7: Create ZIP archive
log_info "Phase 7: Creating ZIP archive..."

cd "$WORKING_DIR"
ZIP_FILE="${ARCHIVE_NAME}.zip"

if command -v zip &> /dev/null; then
    zip -r -q "$ZIP_FILE" "$ARCHIVE_NAME"
    log_info "  Created: $ZIP_FILE"
else
    log_warn "  zip command not found, skipping compression"
    ZIP_FILE=""
fi

# Phase 8: Copy to instances directory
log_info "Phase 8: Archiving to instances directory..."

INSTANCES_DIR="instances/${ORG_ALIAS}/architecture-audits"

if [[ "$ORG_ALIAS" != "unknown" ]]; then
    mkdir -p "$INSTANCES_DIR"

    if [[ -n "$ZIP_FILE" && -f "$ZIP_FILE" ]]; then
        cp "$ZIP_FILE" "$INSTANCES_DIR/"
        log_info "  Copied to: $INSTANCES_DIR/$ZIP_FILE"
    else
        # Copy directory if no ZIP
        cp -r "$ARCHIVE_NAME" "$INSTANCES_DIR/"
        log_info "  Copied to: $INSTANCES_DIR/$ARCHIVE_NAME"
    fi
else
    log_warn "  Org alias unknown, skipping instance copy"
fi

# Phase 9: Cleanup (optional - keep for review)
# Uncomment to auto-cleanup working directory
# rm -rf "$ARCHIVE_DIR"

echo ""
log_info "✅ Architecture audit packaging complete"
echo ""
echo "  Archive: $ARCHIVE_NAME"
echo "  Reports: $REPORT_COUNT"
echo "  Diagrams: $DIAGRAM_COUNT"
echo "  Data Files: $DATA_COUNT"
echo ""

# Output result for hook system
if [[ -n "$ZIP_FILE" ]]; then
    echo "PACKAGE_PATH=$WORKING_DIR/$ZIP_FILE"
else
    echo "PACKAGE_PATH=$WORKING_DIR/$ARCHIVE_NAME"
fi
echo "PACKAGE_NAME=$ARCHIVE_NAME"
echo "TOTAL_ARTIFACTS=$((REPORT_COUNT + DIAGRAM_COUNT + DATA_COUNT))"

exit 0
