#!/bin/bash

#
# Automatic Routing Setup Script
#
# Configures automatic agent routing in Claude Code settings.
# This script updates .claude/settings.json to enable the routing hook.
#
# Version: 1.0.0
# Date: 2025-01-08
#

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOK_PATH="$PLUGIN_ROOT/hooks/user-prompt-router.sh"

# Find Claude settings files
HOME_DIR="${HOME}"
PROJECT_SETTINGS=".claude/settings.json"
USER_SETTINGS="$HOME_DIR/.claude/settings.json"

# Configuration
ENABLE_AUTO_ROUTING="${ENABLE_AUTO_ROUTING:-1}"
ROUTING_CONFIDENCE_THRESHOLD="${ROUTING_CONFIDENCE_THRESHOLD:-0.7}"
COMPLEXITY_THRESHOLD="${COMPLEXITY_THRESHOLD:-0.7}"
ROUTING_VERBOSE="${ROUTING_VERBOSE:-0}"

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Automatic Agent Routing Setup                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to check if hook is already configured
check_existing_hook() {
    local settings_file="$1"
    if [ -f "$settings_file" ]; then
        if grep -q "user-prompt-submit" "$settings_file" 2>/dev/null; then
            return 0
        fi
    fi
    return 1
}

# Function to backup settings file
backup_settings() {
    local settings_file="$1"
    local backup_file="${settings_file}.backup.$(date +%Y%m%d%H%M%S)"

    if [ -f "$settings_file" ]; then
        cp "$settings_file" "$backup_file"
        echo -e "${GREEN}✓${NC} Created backup: $backup_file"
    fi
}

# Function to add hook to settings
add_hook_to_settings() {
    local settings_file="$1"
    local relative_hook_path="$2"

    # Create .claude directory if it doesn't exist
    mkdir -p "$(dirname "$settings_file")"

    # Check if file exists and has content
    if [ -f "$settings_file" ] && [ -s "$settings_file" ]; then
        # File exists with content - parse and update
        if command -v jq >/dev/null 2>&1; then
            # Use jq for clean JSON manipulation
            local temp_file=$(mktemp)
            jq --arg hook "$relative_hook_path" '.hooks."user-prompt-submit" = $hook' "$settings_file" > "$temp_file"
            mv "$temp_file" "$settings_file"
        else
            # Fallback: manual JSON manipulation
            echo -e "${YELLOW}⚠${NC} jq not found - using manual JSON update"

            # Remove closing brace
            sed -i '$ d' "$settings_file"

            # Check if hooks section exists
            if grep -q '"hooks"' "$settings_file"; then
                # Update hooks section
                sed -i 's/"hooks": {/"hooks": {\n    "user-prompt-submit": "'"$relative_hook_path"'",/' "$settings_file"
            else
                # Add hooks section
                echo '  "hooks": {' >> "$settings_file"
                echo '    "user-prompt-submit": "'"$relative_hook_path"'"' >> "$settings_file"
                echo '  }' >> "$settings_file"
            fi

            # Add closing brace
            echo '}' >> "$settings_file"
        fi
    else
        # File doesn't exist or is empty - create new
        cat > "$settings_file" << EOF
{
  "hooks": {
    "user-prompt-submit": "$relative_hook_path"
  }
}
EOF
    fi

    echo -e "${GREEN}✓${NC} Hook configured in $settings_file"
}

# Function to create .env file with defaults
create_env_file() {
    local env_file=".env"

    if [ ! -f "$env_file" ]; then
        cat > "$env_file" << EOF
# Automatic Agent Routing Configuration
# Generated by setup-auto-routing.sh

# Enable/disable auto-routing (1=enabled, 0=disabled)
ENABLE_AUTO_ROUTING=$ENABLE_AUTO_ROUTING

# Confidence threshold for auto-routing (0.0-1.0)
# Agents with confidence >= this value will be auto-selected
ROUTING_CONFIDENCE_THRESHOLD=$ROUTING_CONFIDENCE_THRESHOLD

# Complexity threshold for required routing (0.0-1.0)
# Tasks with complexity >= this value MUST use an agent
COMPLEXITY_THRESHOLD=$COMPLEXITY_THRESHOLD

# Hook timeout in seconds (default: 5)
HOOK_TIMEOUT=5

# Enable verbose logging (1=enabled, 0=disabled)
ROUTING_VERBOSE=$ROUTING_VERBOSE

# Log file location
ROUTING_LOG_FILE=/tmp/routing-hook.log
EOF
        echo -e "${GREEN}✓${NC} Created .env file with routing defaults"
    else
        echo -e "${YELLOW}⚠${NC} .env file already exists - skipping"
        echo -e "   Add routing variables manually if needed"
    fi
}

# Main setup process
main() {
    echo "Checking prerequisites..."

    # Check if hook file exists
    if [ ! -f "$HOOK_PATH" ]; then
        echo -e "${RED}✗${NC} Hook file not found: $HOOK_PATH"
        echo -e "   Make sure cross-platform-plugin is installed correctly"
        exit 1
    fi

    echo -e "${GREEN}✓${NC} Hook file found"

    # Make hook executable
    chmod +x "$HOOK_PATH"
    echo -e "${GREEN}✓${NC} Hook is executable"

    echo ""
    echo "Setup options:"
    echo "1. Project scope (recommended for team projects)"
    echo "2. User scope (applies to all your projects)"
    echo "3. Both scopes"
    echo ""
    read -p "Select scope (1-3): " scope_choice

    case $scope_choice in
        1)
            echo ""
            echo "Setting up project scope..."

            if check_existing_hook "$PROJECT_SETTINGS"; then
                echo -e "${YELLOW}⚠${NC} Hook already configured in $PROJECT_SETTINGS"
                read -p "Overwrite? (y/n): " overwrite
                if [ "$overwrite" != "y" ]; then
                    echo "Skipping project scope setup"
                else
                    backup_settings "$PROJECT_SETTINGS"
                    add_hook_to_settings "$PROJECT_SETTINGS" ".claude-plugins/cross-platform-plugin/hooks/user-prompt-router.sh"
                fi
            else
                backup_settings "$PROJECT_SETTINGS"
                add_hook_to_settings "$PROJECT_SETTINGS" ".claude-plugins/cross-platform-plugin/hooks/user-prompt-router.sh"
            fi

            create_env_file
            ;;
        2)
            echo ""
            echo "Setting up user scope..."

            if check_existing_hook "$USER_SETTINGS"; then
                echo -e "${YELLOW}⚠${NC} Hook already configured in $USER_SETTINGS"
                read -p "Overwrite? (y/n): " overwrite
                if [ "$overwrite" != "y" ]; then
                    echo "Skipping user scope setup"
                else
                    backup_settings "$USER_SETTINGS"
                    # Use absolute path for user scope
                    add_hook_to_settings "$USER_SETTINGS" "$HOOK_PATH"
                fi
            else
                backup_settings "$USER_SETTINGS"
                add_hook_to_settings "$USER_SETTINGS" "$HOOK_PATH"
            fi
            ;;
        3)
            echo ""
            echo "Setting up both scopes..."

            # Project scope
            if check_existing_hook "$PROJECT_SETTINGS"; then
                echo -e "${YELLOW}⚠${NC} Hook already configured in $PROJECT_SETTINGS"
            else
                backup_settings "$PROJECT_SETTINGS"
                add_hook_to_settings "$PROJECT_SETTINGS" ".claude-plugins/cross-platform-plugin/hooks/user-prompt-router.sh"
            fi

            # User scope
            if check_existing_hook "$USER_SETTINGS"; then
                echo -e "${YELLOW}⚠${NC} Hook already configured in $USER_SETTINGS"
            else
                backup_settings "$USER_SETTINGS"
                add_hook_to_settings "$USER_SETTINGS" "$HOOK_PATH"
            fi

            create_env_file
            ;;
        *)
            echo -e "${RED}✗${NC} Invalid choice"
            exit 1
            ;;
    esac

    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}✓ Setup Complete!${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
    echo ""
    echo "Automatic routing is now enabled!"
    echo ""
    echo "Configuration:"
    echo "  • Confidence threshold: $ROUTING_CONFIDENCE_THRESHOLD (tasks >= this auto-route)"
    echo "  • Complexity threshold: $COMPLEXITY_THRESHOLD (tasks >= this MUST route)"
    echo "  • Verbose logging: $ROUTING_VERBOSE"
    echo ""
    echo "Override controls:"
    echo "  [DIRECT] - Skip routing entirely"
    echo "  [USE: agent-name] - Force specific agent"
    echo "  [SKIP_ROUTING] - Skip routing"
    echo ""
    echo "Test the setup:"
    echo "  1. Start a new Claude Code session"
    echo "  2. Try: \"Deploy validation rules to production\""
    echo "  3. Should automatically route to release-coordinator"
    echo ""
    echo "Troubleshooting:"
    echo "  • Check logs: tail -f /tmp/routing-hook.log"
    echo "  • Health check: /routing-health"
    echo "  • Disable: export ENABLE_AUTO_ROUTING=0"
    echo ""
    echo "Documentation: .claude-plugins/cross-platform-plugin/AUTO_ROUTING_SETUP.md"
}

# Run main
main

exit 0
