#!/bin/bash

echo "================================================"
echo "🚀 RevPal Integration Folders Setup"
echo "================================================"
echo ""
echo "Your RevPal folder exists with business documents."
echo "Now we need to add automation folders."
echo ""
echo "📁 CURRENT STRUCTURE:"
echo "RevPal/"
echo "  ├── Contract Templates/"
echo "  ├── Contracts/"
echo "  ├── Funding/"
echo "  ├── Logos/"
echo "  ├── MNDAs/"
echo "  └── [other business files]"
echo ""
echo "📋 FOLDERS TO ADD:"
echo "RevPal/"
echo "  ├── Documentation/        <- For integration docs"
echo "  ├── Reports/             <- For automated reports"
echo "  │   ├── Salesforce/"
echo "  │   ├── HubSpot/"
echo "  │   └── Combined/"
echo "  ├── Templates/           <- For code/email templates"
echo "  │   ├── Salesforce/"
echo "  │   └── HubSpot/"
echo "  ├── Compliance/          <- For compliance docs"
echo "  └── Archives/            <- For historical data"
echo ""
echo "================================================"
echo ""
echo "🔧 TWO OPTIONS TO COMPLETE SETUP:"
echo ""
echo "OPTION 1: Re-authenticate with full permissions"
echo "----------------------------------------"
echo "1. Run this command:"
echo "   npx @modelcontextprotocol/server-gdrive auth --reset"
echo ""
echo "2. In the browser popup:"
echo "   - Sign in to Google"
echo "   - Grant ALL requested permissions"
echo "   - Including 'Create, edit, and delete files'"
echo ""
echo "3. Run this script to create folders:"
echo "   node scripts/create-revpal-folders.js"
echo ""
echo "OPTION 2: Create folders manually (5 minutes)"
echo "----------------------------------------"
echo "1. Open Google Drive: https://drive.google.com"
echo "2. Navigate to your RevPal folder"
echo "3. Create these folders:"
echo "   • Documentation"
echo "   • Reports (with Salesforce, HubSpot, Combined subfolders)"
echo "   • Templates (with Salesforce, HubSpot subfolders)"
echo "   • Compliance"
echo "   • Archives"
echo ""
echo "================================================"
echo ""
echo "✅ WHAT WORKS NOW (even without folder creation):"
echo "  • Read files from RevPal folder"
echo "  • List all your Drive contents"
echo "  • Export reports (once folders exist)"
echo "  • Access existing documents"
echo ""
echo "Would you like to:"
echo "  1. Re-authenticate now"
echo "  2. Create folders manually"
echo "  3. Test current capabilities"
echo ""