/**
 * Integration tests for AdminHandlers — full CRUD lifecycle
 */

'use strict';

const os = require('os');
const fs = require('fs');
const path = require('path');
const { createCustomizationLayer } = require('../../customization');

const PLUGIN_ROOT = path.resolve(__dirname, '../../../..');

describe('AdminHandlers (integration)', () => {
  let layer, tempDir;

  beforeEach(async () => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'opspal-admin-'));

    layer = await createCustomizationLayer({
      pluginRoot: PLUGIN_ROOT,
      globalDir: path.join(tempDir, 'site')
    });
    layer.store.orgDir = path.join(tempDir, 'tenant');
    await layer.store.ensureDirectories('both');

    // Point audit log to temp dir
    layer.auditLog.logDir = path.join(tempDir, 'audit');
    layer.auditLog.logFile = path.join(tempDir, 'audit', 'audit.jsonl');
  });

  afterEach(() => {
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  test('list returns packaged defaults', async () => {
    const all = await layer.admin.list({ scope: 'global' });
    expect(all.length).toBeGreaterThan(10);
    expect(all.every(r => r._scope === 'global')).toBe(true);
  });

  test('clone creates a custom resource from default', async () => {
    const cloned = await layer.admin.clone('brand:color-palette:default', {
      title: 'My Custom Palette'
    });

    expect(cloned.resource_id).toBe('brand:color-palette:default');
    expect(cloned.source_type).toBe('custom');
    expect(cloned.status).toBe('draft');
    expect(cloned.title).toBe('My Custom Palette');
    expect(cloned.source_resource_id).toBe('brand:color-palette:default');
    expect(cloned.source_version).toBeDefined();
    expect(cloned.source_checksum).toBeDefined();
  });

  test('clone → edit → publish → resolve lifecycle', async () => {
    // Clone
    await layer.admin.clone('brand:color-palette:default', {
      title: 'Acme Colors'
    });

    // Edit
    const edited = await layer.admin.edit('brand:color-palette:default', {
      content: { grape: '#FF0000', indigo: '#00FF00', apricot: '#0000FF', sand: '#FFFFFF', green: '#00FF00' }
    });
    expect(edited.content.grape).toBe('#FF0000');

    // Publish
    const published = await layer.admin.publish('brand:color-palette:default');
    expect(published.status).toBe('published');

    // Resolve — should return custom version
    layer.resolver.invalidateCache();
    const palette = await layer.resolver.resolveColorPalette();
    expect(palette.grape).toBe('#FF0000');
  });

  test('revert deletes custom and falls back to default', async () => {
    // Clone and publish
    await layer.admin.clone('brand:color-palette:default');
    await layer.admin.publish('brand:color-palette:default');

    // Revert
    const result = await layer.admin.revert('brand:color-palette:default');
    expect(result.reverted).toBe(true);

    // Resolve — should return packaged default
    layer.resolver.invalidateCache();
    const palette = await layer.resolver.resolveColorPalette();
    expect(palette.grape).toBe('#5F3B8C');
  });

  test('archive deactivates resource', async () => {
    await layer.admin.clone('brand:color-palette:default');
    await layer.admin.publish('brand:color-palette:default');
    await layer.admin.archive('brand:color-palette:default');

    // Resolve should fall through to packaged default (archived is not published)
    layer.resolver.invalidateCache();
    const palette = await layer.resolver.resolveColorPalette();
    expect(palette.grape).toBe('#5F3B8C');
  });

  test('create makes a net-new custom resource', async () => {
    const created = await layer.admin.create({
      resource_id: 'template:pdf-cover:custom-report',
      resource_type: 'template',
      title: 'Custom Report Cover',
      content: '# Custom Report\n\nGenerated by Acme Corp',
      metadata: { subType: 'pdf-cover', fileType: 'markdown' }
    });

    expect(created.resource_id).toBe('template:pdf-cover:custom-report');
    expect(created.source_resource_id).toBeNull();
    expect(created.checksum).toMatch(/^sha256:/);
  });

  test('clone throws for duplicate', async () => {
    await layer.admin.clone('brand:color-palette:default');
    await expect(layer.admin.clone('brand:color-palette:default'))
      .rejects.toThrow('already exists');
  });

  test('edit throws for nonexistent', async () => {
    await expect(layer.admin.edit('nonexistent:id', { title: 'x' }))
      .rejects.toThrow('not found');
  });

  test('compare works for cloned resource', async () => {
    await layer.admin.clone('brand:color-palette:default');
    await layer.admin.edit('brand:color-palette:default', {
      content: { grape: '#MODIFIED', indigo: '#3E4A61' }
    });

    const diff = await layer.admin.compare('brand:color-palette:default');
    expect(diff.hasChanges).toBe(true);
  });

  test('audit log records mutations', async () => {
    await layer.admin.clone('brand:color-palette:default');
    await layer.admin.publish('brand:color-palette:default');
    await layer.admin.revert('brand:color-palette:default');

    const entries = layer.auditLog.query({ resourceId: 'brand:color-palette:default' });
    expect(entries.length).toBe(3);
    expect(entries.map(e => e.action)).toEqual(
      expect.arrayContaining(['clone', 'update', 'revert'])
    );
  });

  test('list includes both global and custom resources', async () => {
    await layer.admin.clone('brand:color-palette:default');

    const all = await layer.admin.list();
    const custom = all.filter(r => r.source_type === 'custom');
    const core = all.filter(r => r.source_type === 'core');

    expect(custom.length).toBeGreaterThan(0);
    expect(core.length).toBeGreaterThan(0);
  });
});
